"use client";import { useEffect,useState } from "react";import { defaultContent,type SiteContent } from "../site-data";
type Tab="info"|"plans"|"coaches"|"schedule";
export default function Editor({email,signout}:{email:string;signout:string}){const[c,setC]=useState<SiteContent>(defaultContent),[tab,setTab]=useState<Tab>("info"),[msg,setMsg]=useState("Ачаалж байна...");useEffect(()=>{fetch("/api/admin/content").then(async r=>{const x=await r.json();if(!r.ok)throw Error(x.error);setC(x);setMsg("")}).catch(e=>setMsg(e.message))},[]);async function save(){setMsg("Хадгалж байна...");const r=await fetch("/api/admin/content",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(c)});const x=await r.json();setMsg(r.ok?"✓ Амжилттай хадгаллаа":x.error)}
return <main className="admin-shell"><aside><a className="admin-logo" href="/"><img src="/adrenaline-logo.jpg" alt=""/><b>ADRENALINE<br/><small>CONTROL CENTER</small></b></a>{([['info','Ерөнхий'],['plans','Гишүүнчлэл'],['coaches','Дасгалжуулагч'],['schedule','Хуваарь']] as [Tab,string][]).map(([k,v])=><button className={tab===k?'active':''} onClick={()=>setTab(k)} key={k}>{v}</button>)}<footer>{email}<a href={signout}>Гарах</a></footer></aside><section className="admin-work"><header><div><small>САЙТЫН УДИРДЛАГА</small><h1>{tab}</h1></div><div><a href="/" target="_blank">Сайт харах ↗</a><button onClick={save}>ӨӨРЧЛӨЛТ ХАДГАЛАХ</button></div></header>{msg&&<p className="admin-msg">{msg}</p>}
{tab==='info'&&<Card title="Холбоо барих мэдээлэл"><div className="formgrid">{Object.entries(c.siteInfo).map(([k,v])=><Field key={k} label={k} value={v||''} change={x=>setC({...c,siteInfo:{...c.siteInfo,[k]:x}})}/>)}</div></Card>}
{tab==='plans'&&c.membershipPlans.map((p,i)=><Card key={p.id} title={p.name}><div className="formgrid"><Field label="Нэр" value={p.name} change={v=>plan(i,{name:v})}/><Field label="Хугацаа" value={p.duration} change={v=>plan(i,{duration:v})}/><Field label="Үнэ" value={String(p.price)} type="number" change={v=>plan(i,{price:Number(v)})}/><Field label="Тайлбар" value={p.description} change={v=>plan(i,{description:v})}/><Field wide area label="Давуу талууд (мөр бүрт нэг)" value={p.features.join('\n')} change={v=>plan(i,{features:v.split('\n').filter(Boolean)})}/></div></Card>)}
{tab==='coaches'&&c.coaches.map((p,i)=><Card key={p.id||i} title={p.name||p.role}><div className="coachform"><Upload image={p.image} done={v=>coach(i,{image:v})}/><div className="formgrid"><Field label="Нэр" value={p.name||''} change={v=>coach(i,{name:v})}/><Field label="Албан тушаал" value={p.role} change={v=>coach(i,{role:v})}/><Field label="Чиглэл" value={p.focus} change={v=>coach(i,{focus:v})}/><Field area label="Танилцуулга" value={p.copy} change={v=>coach(i,{copy:v})}/></div></div></Card>)}
{tab==='schedule'&&c.schedule.map((d,di)=><Card key={d.day} title={d.day}>{d.sessions.map((s,si)=><div className="sessionrow" key={si}><Field label="Цаг" value={s[0]} change={v=>session(di,si,0,v)}/><Field label="Хичээл" value={s[1]} change={v=>session(di,si,1,v)}/><button onClick={()=>remove(di,si)}>×</button></div>)}<button className="add" onClick={()=>add(di)}>+ Хичээл нэмэх</button></Card>)}</section></main>;
function plan(i:number,p:Partial<SiteContent['membershipPlans'][number]>){const a=[...c.membershipPlans];a[i]={...a[i],...p};setC({...c,membershipPlans:a})}function coach(i:number,p:Partial<SiteContent['coaches'][number]>){const a=[...c.coaches];a[i]={...a[i],...p};setC({...c,coaches:a})}function session(di:number,si:number,f:0|1,v:string){const a=structuredClone(c.schedule);a[di].sessions[si][f]=v;setC({...c,schedule:a})}function add(di:number){const a=structuredClone(c.schedule);a[di].sessions.push(['18:00','Шинэ хичээл']);setC({...c,schedule:a})}function remove(di:number,si:number){const a=structuredClone(c.schedule);a[di].sessions.splice(si,1);setC({...c,schedule:a})}}
function Card({title,children}:{title:string;children:React.ReactNode}){return <article className="admin-card"><h2>{title}</h2>{children}</article>}function Field({label,value,change,area,type='text',wide}:{label:string;value:string;change:(v:string)=>void;area?:boolean;type?:string;wide?:boolean}){return <label className={wide?'wide':''}><span>{label}</span>{area?<textarea value={value} onChange={e=>change(e.target.value)}/>:<input type={type} value={value} onChange={e=>change(e.target.value)}/>}</label>}
function Upload({image,done}:{image?:string;done:(v:string)=>void}){const[msg,setMsg]=useState('');async function up(f?:File){if(!f)return;setMsg('Оруулж байна...');const b=new FormData();b.append('file',f);const r=await fetch('/api/admin/upload',{method:'POST',body:b});const x=await r.json();if(r.ok){done(x.url);setMsg('✓ Зураг орлоо')}else setMsg(x.error)}return <div className="uploader">{image?<img src={image} alt=""/>:<div>PHOTO</div>}<label>ЗУРАГ ОРУУЛАХ<input type="file" accept="image/*" onChange={e=>up(e.target.files?.[0])}/></label><small>{msg}</small></div>}
