"use client";
import { useEffect, useState } from "react";
import { defaultContent, type CmsBlock, type CmsPage, type SiteContent } from "../site-data";
type Tab="info"|"plans"|"coaches"|"schedule"|"pages";
const menu:[Tab,string][]=[["info","Ерөнхий"],["plans","Гишүүнчлэл"],["coaches","Дасгалжуулагч"],["schedule","Хуваарь"],["pages","Хуудас"]];
const uid=()=>crypto.randomUUID();
export default function Editor({email,signout}:{email:string;signout:string}){
 const[c,setC]=useState<SiteContent>(defaultContent),[tab,setTab]=useState<Tab>("info"),[msg,setMsg]=useState("Ачаалж байна..."),[editing,setEditing]=useState<string|null>(null);
 useEffect(()=>{fetch("/api/admin/content").then(async r=>{const x=await r.json();if(!r.ok)throw Error(x.error);setC({...defaultContent,...x,pages:x.pages||[]});setMsg("")}).catch(e=>setMsg(e.message))},[]);
 async function save(){setMsg("Хадгалж байна...");const r=await fetch("/api/admin/content",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(c)});const x=await r.json();setMsg(r.ok?"✓ Амжилттай хадгаллаа":x.error)}
 const page=c.pages.find(p=>p.id===editing);
 return <main className="admin-shell"><aside><a className="admin-logo" href="/"><img src="/adrenaline-logo.jpg" alt=""/><b>ADRENALINE<br/><small>CONTROL CENTER</small></b></a>{menu.map(([k,v])=><button className={tab===k?'active':''} onClick={()=>{setTab(k);setEditing(null)}} key={k}>{v}</button>)}<footer>{email}<a href={signout}>Гарах</a></footer></aside><section className="admin-work"><header><div><small>САЙТЫН УДИРДЛАГА</small><h1>{editing?"ХУУДАС ЗАСАХ":menu.find(x=>x[0]===tab)?.[1]}</h1></div><div><a href="/" target="_blank">Сайт харах ↗</a><button onClick={save}>ӨӨРЧЛӨЛТ ХАДГАЛАХ</button></div></header>{msg&&<p className="admin-msg">{msg}</p>}
 {tab==='info'&&<Card title="Холбоо барих мэдээлэл"><div className="formgrid">{Object.entries(c.siteInfo).map(([k,v])=><Field key={k} label={k} value={v||''} change={x=>setC({...c,siteInfo:{...c.siteInfo,[k]:x}})}/>)}</div></Card>}
 {tab==='plans'&&c.membershipPlans.map((p,i)=><Card key={p.id} title={p.name}><div className="formgrid"><Field label="Нэр" value={p.name} change={v=>plan(i,{name:v})}/><Field label="Хугацаа" value={p.duration} change={v=>plan(i,{duration:v})}/><Field label="Үнэ" value={String(p.price)} type="number" change={v=>plan(i,{price:Number(v)})}/><Field label="Тайлбар" value={p.description} change={v=>plan(i,{description:v})}/><Field wide area label="Давуу талууд (мөр бүрт нэг)" value={p.features.join('\n')} change={v=>plan(i,{features:v.split('\n').filter(Boolean)})}/></div></Card>)}
 {tab==='coaches'&&c.coaches.map((p,i)=><Card key={p.id||i} title={p.name||p.role}><div className="coachform"><Upload image={p.image} done={v=>coach(i,{image:v})}/><div className="formgrid"><Field label="Нэр" value={p.name||''} change={v=>coach(i,{name:v})}/><Field label="Албан тушаал" value={p.role} change={v=>coach(i,{role:v})}/><Field label="Чиглэл" value={p.focus} change={v=>coach(i,{focus:v})}/><Field area label="Танилцуулга" value={p.copy} change={v=>coach(i,{copy:v})}/></div></div></Card>)}
 {tab==='schedule'&&c.schedule.map((d,di)=><Card key={d.day} title={d.day}>{d.sessions.map((s,si)=><div className="sessionrow" key={si}><Field label="Цаг" value={s[0]} change={v=>session(di,si,0,v)}/><Field label="Хичээл" value={s[1]} change={v=>session(di,si,1,v)}/><button onClick={()=>removeSession(di,si)}>×</button></div>)}<button className="add" onClick={()=>addSession(di)}>+ Хичээл нэмэх</button></Card>)}
 {tab==='pages'&&!page&&<PageList pages={c.pages} add={addPage} edit={setEditing} remove={removePage}/>} {tab==='pages'&&page&&<PageEditor page={page} back={()=>setEditing(null)} change={patch=>updatePage(page.id,patch)} addBlock={type=>addBlock(page.id,type)} updateBlock={(id,patch)=>updateBlock(page.id,id,patch)} removeBlock={id=>removeBlock(page.id,id)}/>} </section></main>;
 function plan(i:number,p:Partial<SiteContent['membershipPlans'][number]>){const a=[...c.membershipPlans];a[i]={...a[i],...p};setC({...c,membershipPlans:a})}function coach(i:number,p:Partial<SiteContent['coaches'][number]>){const a=[...c.coaches];a[i]={...a[i],...p};setC({...c,coaches:a})}function session(di:number,si:number,f:0|1,v:string){const a=structuredClone(c.schedule);a[di].sessions[si][f]=v;setC({...c,schedule:a})}function addSession(di:number){const a=structuredClone(c.schedule);a[di].sessions.push(['18:00','Шинэ хичээл']);setC({...c,schedule:a})}function removeSession(di:number,si:number){const a=structuredClone(c.schedule);a[di].sessions.splice(si,1);setC({...c,schedule:a})}
 function addPage(){const p:CmsPage={id:uid(),title:"Шинэ хуудас",slug:`page-${Date.now()}`,excerpt:"Хуудасны товч танилцуулга",status:"draft",showInNav:false,seoTitle:"",seoDescription:"",blocks:[]};setC({...c,pages:[...c.pages,p]});setEditing(p.id)}function removePage(id:string){if(!confirm("Энэ хуудсыг устгах уу?"))return;setC({...c,pages:c.pages.filter(p=>p.id!==id)})}function updatePage(id:string,patch:Partial<CmsPage>){setC({...c,pages:c.pages.map(p=>p.id===id?{...p,...patch}:p)})}function addBlock(pid:string,type:CmsBlock['type']){const b:CmsBlock={id:uid(),type,title:type==='heading'?"Шинэ гарчиг":"",body:type==='text'?"Энд текстээ бичнэ үү.":"",buttonLabel:type==='cta'?"ХОЛБОГДОХ":"",buttonUrl:type==='cta'?"/#contact":""};updatePage(pid,{blocks:[...(c.pages.find(p=>p.id===pid)?.blocks||[]),b]})}function updateBlock(pid:string,bid:string,patch:Partial<CmsBlock>){const p=c.pages.find(x=>x.id===pid);if(p)updatePage(pid,{blocks:p.blocks.map(b=>b.id===bid?{...b,...patch}:b)})}function removeBlock(pid:string,bid:string){const p=c.pages.find(x=>x.id===pid);if(p)updatePage(pid,{blocks:p.blocks.filter(b=>b.id!==bid)})}
}
function PageList({pages,add,edit,remove}:{pages:CmsPage[];add:()=>void;edit:(id:string)=>void;remove:(id:string)=>void}){return <div className="page-manager"><div className="page-manager-head"><div><h2>Хуудас</h2><p>Нүүр хуудаснаас тусдаа мэдээллийн хуудсууд.</p></div><button onClick={add}>+ ШИНЭ ХУУДАС</button></div>{pages.length===0?<div className="empty-pages"><b>Одоогоор нэмэлт хуудас алга.</b><p>“Шинэ хуудас” товчоор эхний хуудсаа үүсгэнэ үү.</p></div>:<div className="page-list">{pages.map(p=><article key={p.id}><div><span className={p.status}>{p.status==='published'?'НИЙТЭЛСЭН':'НООРОГ'}</span><h3>{p.title}</h3><small>/{p.slug}</small></div><div><a href={`/${p.slug}`} target="_blank">Харах ↗</a><button onClick={()=>edit(p.id)}>Засах</button><button className="danger" onClick={()=>remove(p.id)}>Устгах</button></div></article>)}</div>}</div>}
function PageEditor({page,back,change,addBlock,updateBlock,removeBlock}:{page:CmsPage;back:()=>void;change:(p:Partial<CmsPage>)=>void;addBlock:(t:CmsBlock['type'])=>void;updateBlock:(id:string,p:Partial<CmsBlock>)=>void;removeBlock:(id:string)=>void}){return <div className="page-editor"><button className="back" onClick={back}>← ХУУДСЫН ЖАГСААЛТ</button><Card title="Үндсэн тохиргоо"><div className="formgrid"><Field label="Хуудасны нэр" value={page.title} change={v=>change({title:v})}/><Field label="URL slug" value={page.slug} change={v=>change({slug:slugify(v)})}/><Field wide area label="Товч танилцуулга" value={page.excerpt} change={v=>change({excerpt:v})}/><Select label="Төлөв" value={page.status} change={v=>change({status:v as CmsPage['status']})} options={[["draft","Ноорог"],["published","Нийтэлсэн"]]}/><label className="check"><input type="checkbox" checked={page.showInNav} onChange={e=>change({showInNav:e.target.checked})}/> Үндсэн цэсэнд харуулах</label></div><div className="hero-upload"><span>Hero зураг</span><Upload image={page.heroImage} done={v=>change({heroImage:v})}/></div></Card><Card title="SEO"><div className="formgrid"><Field label="SEO гарчиг" value={page.seoTitle} change={v=>change({seoTitle:v})}/><Field label="Meta тайлбар" value={page.seoDescription} change={v=>change({seoDescription:v})}/></div></Card><div className="blocks-head"><h2>Контентын блокууд</h2><div><button onClick={()=>addBlock('heading')}>+ Гарчиг</button><button onClick={()=>addBlock('text')}>+ Текст</button><button onClick={()=>addBlock('image')}>+ Зураг</button><button onClick={()=>addBlock('cta')}>+ CTA</button></div></div>{page.blocks.map((b,i)=><BlockEditor key={b.id} block={b} index={i} change={p=>updateBlock(b.id,p)} remove={()=>removeBlock(b.id)}/>)}</div>}
function BlockEditor({block,index,change,remove}:{block:CmsBlock;index:number;change:(p:Partial<CmsBlock>)=>void;remove:()=>void}){return <Card title={`${index+1}. ${block.type.toUpperCase()}`}><button className="block-remove" onClick={remove}>Устгах</button><div className="formgrid">{block.type==='heading'&&<Field wide label="Гарчиг" value={block.title||''} change={v=>change({title:v})}/>} {block.type==='text'&&<Field wide area label="Текст" value={block.body||''} change={v=>change({body:v})}/>} {block.type==='image'&&<><Upload image={block.image} done={v=>change({image:v})}/><Field label="Зургийн тайлбар" value={block.title||''} change={v=>change({title:v})}/></>} {block.type==='cta'&&<><Field label="CTA гарчиг" value={block.title||''} change={v=>change({title:v})}/><Field label="Тайлбар" value={block.body||''} change={v=>change({body:v})}/><Field label="Товчны текст" value={block.buttonLabel||''} change={v=>change({buttonLabel:v})}/><Field label="Товчны холбоос" value={block.buttonUrl||''} change={v=>change({buttonUrl:v})}/></>}</div></Card>}
function Card({title,children}:{title:string;children:React.ReactNode}){return <article className="admin-card"><h2>{title}</h2>{children}</article>}function Field({label,value,change,area,type='text',wide}:{label:string;value:string;change:(v:string)=>void;area?:boolean;type?:string;wide?:boolean}){return <label className={wide?'wide':''}><span>{label}</span>{area?<textarea value={value} onChange={e=>change(e.target.value)}/>:<input type={type} value={value} onChange={e=>change(e.target.value)}/>}</label>}function Select({label,value,change,options}:{label:string;value:string;change:(v:string)=>void;options:string[][]}){return <label><span>{label}</span><select value={value} onChange={e=>change(e.target.value)}>{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>}
function Upload({image,done}:{image?:string;done:(v:string)=>void}){const[msg,setMsg]=useState('');async function up(f?:File){if(!f)return;setMsg('Оруулж байна...');const b=new FormData();b.append('file',f);const r=await fetch('/api/admin/upload',{method:'POST',body:b});const x=await r.json();if(r.ok){done(x.url);setMsg('✓ Зураг орлоо')}else setMsg(x.error)}return <div className="uploader">{image?<img src={image} alt=""/>:<div>PHOTO</div>}<label>ЗУРАГ ОРУУЛАХ<input type="file" accept="image/*" onChange={e=>up(e.target.files?.[0])}/></label><small>{msg}</small></div>}
function slugify(v:string){return v.toLowerCase().trim().replace(/[^a-z0-9-]/g,'-').replace(/-+/g,'-').replace(/^-|-$/g,'')}
